export const REPO_REQ_DATA = 'REPO_REQ_DATA';
export const REPO_RECV_DATA = 'REPO_RECV_DATA';
export const REPO_RECV_ERROR = 'REPO_RECV_ERROR';

export const COMMITT_REQ_DATA = 'COMMITT_REQ_DATA';
export const COMMITT_RECV_DATA = 'COMMITT_RECV_DATA';
export const COMMITT_RECV_ERROR = 'COMMITT_RECV_ERROR';
export const HIDE_COMMITTS = 'HIDE_COMMITTS';

export const SEARCH_TERM = 'SEARCH_TERM';

export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';
